# Site settings
author: Michael Adkins
title: Lifelong Journeys 
header-img: img/home-bg.png
email: mikeadkins1112@gmail.com
copyright_name: Michael Adkins
description: > # this means to ignore newlines until "baseurl:"
  Stepping Up To The Plate
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  michaeladkins50

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
